test: run_long_bignums.cpp:21: void check_long_operators(): Assertion `(a * b).to_string() == amultb' failed.
test: run_long_bignums.cpp:21: void check_long_operators(): Assertion `(a * b).to_string() == amultb' failed.
test: run_long_bignums.cpp:21: void check_long_operators(): Assertion `(a * b).to_string() == amultb' failed.
test: run_long_bignums.cpp:21: void check_long_operators(): Assertion `(a * b).to_string() == amultb' failed.
test: run_long_bignums.cpp:21: void check_long_operators(): Assertion `(a * b).to_string() == amultb' failed.
test: run_long_bignums.cpp:21: void check_long_operators(): Assertion `(a * b).to_string() == amultb' failed.
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
